name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
        
      - name: Install Protoc
        uses: arduino/setup-protoc@master
          
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: RUST_LOG=debug cargo test --verbose -- --test-threads=1
